# Generated by Django 4.1.2 on 2022-10-31 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default=datetime.datetime(2022, 10, 31, 23, 3, 28, 644237, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
